"""Catalogo de demostracion: categorias, marcas y ~150 productos ficticios.

Separado de seed.py para que el script de carga quede corto y los datos sean
faciles de editar. Todas las marcas y productos son inventados.

Formato de cada producto:
    (nombre, marca, subcategoria, unidad, precio, claim)

El precio esta en pesos argentinos y es coherente entre categorias.
"""

# --------------------------------------------------------------------------- #
# Categorias: (slug, nombre, icono, descripcion)
# --------------------------------------------------------------------------- #
CATEGORIES = [
    ("hogar", "Limpieza del hogar", "🏠", "Multiuso, muebles y limpieza general de todos los ambientes."),
    ("cocina", "Cocina", "🍳", "Desengrasantes, limpiadores de horno y todo para la mesada."),
    ("bano", "Baño", "🚿", "Antisarro, limpiadores de inodoro y cuidado de azulejos."),
    ("lavanderia", "Lavandería", "🧺", "Jabones líquidos y en polvo para el lavarropas."),
    ("desinfectantes", "Desinfectantes", "🦠", "Lavandinas y sanitizantes de acción probada."),
    ("detergentes", "Detergentes", "🧽", "Concentrados para vajilla con alto rendimiento."),
    ("aromatizantes", "Aromatizantes", "🌿", "Ambientales, difusores y perfumes para textiles."),
    ("papel", "Papel e higiene", "🧻", "Papel higiénico, servilletas y rollos de cocina."),
    ("accesorios", "Accesorios de limpieza", "🧹", "Escobas, mopas, guantes, esponjas y baldes."),
    ("pisos", "Productos para pisos", "🪣", "Limpiadores, ceras y protectores para cada superficie."),
    ("ropa", "Productos para ropa", "👕", "Suavizantes, quitamanchas y perfumantes textiles."),
    ("profesional", "Productos profesionales", "🏢", "Bidones y concentrados de uso industrial."),
]

BRANDS = [
    "Brillex", "UltraClean", "Nevada", "Aromia", "PuroHogar", "Rindex",
    "Espumel", "Vitalix", "CleanPro", "Suavia", "Papelia", "Fibrex",
    "Duramax", "Verdalia",
]

# --------------------------------------------------------------------------- #
# Productos por categoria
# --------------------------------------------------------------------------- #
PRODUCTS = {
    # ---------------------------------------------------------------- hogar --
    "hogar": [
        ("Limpiador multiuso Lavanda", "Brillex", "Multiuso", "900 ml", 2890,
         "Limpia y perfuma mesadas, muebles y superficies lavables sin dejar residuo."),
        ("Limpiador multiuso Marina", "Brillex", "Multiuso", "900 ml", 2890,
         "Fórmula de secado rápido con fragancia fresca de brisa marina."),
        ("Limpiador multiuso Citrus", "UltraClean", "Multiuso", "1 L", 3150,
         "Con extracto de limón, corta la grasa liviana del uso diario."),
        ("Multiuso concentrado Eucalipto", "Verdalia", "Multiuso", "500 ml", 3980,
         "Rinde hasta 10 litros diluido: una tapita por balde."),
        ("Limpiador de muebles con cera", "PuroHogar", "Muebles", "400 ml", 4250,
         "Nutre la madera y realza el brillo natural sin engrasar."),
        ("Lustramuebles en aerosol", "PuroHogar", "Muebles", "360 ml", 4690,
         "Repele el polvo hasta 7 días y deja terminación satinada."),
        ("Limpiavidrios con gatillo", "Brillex", "Vidrios", "500 ml", 2450,
         "Evapora sin marcas en vidrios, espejos y pantallas de TV."),
        ("Limpiavidrios repuesto económico", "Brillex", "Vidrios", "1 L", 3290,
         "Recarga rendidora para reutilizar el gatillo original."),
        ("Limpiador de acero inoxidable", "UltraClean", "Superficies", "400 ml", 5120,
         "Elimina huellas y devuelve el brillo a heladeras y campanas."),
        ("Limpiador de pantallas y electrónica", "CleanPro", "Superficies", "250 ml", 4380,
         "Sin alcohol agresivo: seguro para notebooks, celulares y monitores."),
        ("Removedor de polvo para persianas", "PuroHogar", "Muebles", "500 ml", 3760,
         "Fórmula antiestática que evita que el polvo vuelva a adherirse."),
        ("Limpiador de tapizados en espuma", "Espumel", "Tapizados", "450 ml", 5890,
         "Espuma activa que levanta manchas de sillones y alfombras."),
        ("Jabón blanco líquido multiuso", "Rindex", "Multiuso", "1 L", 2190,
         "Clásico jabón neutro para lavar a mano cualquier superficie."),
        ("Alcohol en gel sanitizante hogar", "Vitalix", "Higiene", "500 ml", 2640,
         "70% de alcohol con glicerina para no resecar las manos."),
    ],
    # --------------------------------------------------------------- cocina --
    "cocina": [
        ("Desengrasante de cocina en gatillo", "UltraClean", "Desengrasantes", "500 ml", 3480,
         "Disuelve la grasa quemada de hornallas y azulejos en 60 segundos."),
        ("Desengrasante extra fuerte", "UltraClean", "Desengrasantes", "1 L", 5290,
         "Para grasa acumulada en campanas y frituras intensas."),
        ("Limpiahornos en espuma", "Espumel", "Hornos", "400 ml", 5750,
         "Se adhiere a superficies verticales y actúa sobre carbonizados."),
        ("Limpiador de parrillas", "Duramax", "Hornos", "750 ml", 6120,
         "Ataca la costra de la parrilla sin necesidad de rasquetear."),
        ("Limpiador de mesadas de granito", "PuroHogar", "Superficies", "500 ml", 4890,
         "pH neutro: limpia sin opacar mármol, granito ni cuarzo."),
        ("Limpiador de microondas", "Brillex", "Hornos", "400 ml", 3690,
         "Elimina salpicaduras y olores sin dejar aroma químico en la comida."),
        ("Antigrasa para azulejos", "Rindex", "Desengrasantes", "900 ml", 3990,
         "Deja los azulejos de la cocina brillantes y sin película grasosa."),
        ("Limpiador de heladeras y freezer", "Vitalix", "Superficies", "500 ml", 4210,
         "Desinfecta el interior sin dejar residuos de olor en los alimentos."),
        ("Bicarbonato limpiador en polvo", "Verdalia", "Polvos", "500 g", 2380,
         "Abrasivo suave y biodegradable para ollas y bachas."),
        ("Crema limpiadora para bachas", "Brillex", "Polvos", "750 g", 3420,
         "Micropartículas que pulen el acero sin rayarlo."),
        ("Destapacañerías en gel", "Duramax", "Cañerías", "1 L", 6480,
         "Gel denso que atraviesa el agua estancada y disuelve la grasa."),
        ("Limpiador de tablas y utensilios", "Vitalix", "Higiene", "500 ml", 3860,
         "Apto para contacto con alimentos, elimina olores de tabla y cuchillos."),
        ("Quitagrasa biodegradable", "Verdalia", "Desengrasantes", "750 ml", 4560,
         "Base vegetal, sin fosfatos, con la misma potencia desengrasante."),
    ],
    # ----------------------------------------------------------------- bano --
    "bano": [
        ("Limpiador de baño antisarro", "Brillex", "Antisarro", "750 ml", 3290,
         "Disuelve el sarro de canillas y mamparas sin frotar."),
        ("Limpiador de baño en gel", "Brillex", "Inodoros", "500 ml", 3480,
         "Gel adherente que actúa bajo el borde del inodoro."),
        ("Pastillas para mochila de inodoro", "Aromia", "Inodoros", "2 un.", 2790,
         "Cada descarga limpia y perfuma el agua durante 30 días."),
        ("Bloque adhesivo para inodoro", "Aromia", "Inodoros", "3 un.", 3140,
         "Se adhiere a la porcelana y libera fragancia con cada descarga."),
        ("Desinfectante de baño con lavanda", "Vitalix", "Desinfección", "900 ml", 3980,
         "Elimina el 99,9% de bacterias en superficies del baño."),
        ("Limpiador de juntas y azulejos", "Duramax", "Azulejos", "500 ml", 4620,
         "Blanquea las juntas ennegrecidas por la humedad."),
        ("Antihongos para mamparas", "Duramax", "Azulejos", "500 ml", 4980,
         "Previene la reaparición de moho hasta 4 semanas."),
        ("Limpiador de mamparas de vidrio", "CleanPro", "Antisarro", "500 ml", 4120,
         "Crea una película que repele el agua y retrasa el sarro."),
        ("Desodorante de ambientes para baño", "Aromia", "Desinfección", "360 ml", 3260,
         "Neutraliza olores en lugar de taparlos con perfume."),
        ("Limpiador cremoso para bañeras", "Espumel", "Azulejos", "750 ml", 3740,
         "Abrasivo suave que no raya el acrílico ni el esmalte."),
        ("Jabón líquido para manos Aloe", "Suavia", "Higiene", "400 ml", 2580,
         "Con aloe vera y glicerina: higieniza sin resecar."),
        ("Recarga jabón de manos Aloe", "Suavia", "Higiene", "1 L", 4390,
         "Formato económico para recargar el dispenser del baño."),
    ],
    # ----------------------------------------------------------- lavanderia --
    "lavanderia": [
        ("Jabón líquido para ropa Clásico", "Rindex", "Jabón líquido", "3 L", 8990,
         "Rinde 60 lavados y se disuelve incluso en agua fría."),
        ("Jabón líquido para ropa Blanco Total", "Rindex", "Jabón líquido", "3 L", 9450,
         "Con abrillantadores ópticos que recuperan los blancos."),
        ("Jabón líquido ropa de color", "Rindex", "Jabón líquido", "1,8 L", 6480,
         "Protege la intensidad de los colores lavado tras lavado."),
        ("Jabón líquido bebé hipoalergénico", "Suavia", "Jabón líquido", "1,5 L", 7290,
         "Sin perfumes ni colorantes, testeado dermatológicamente."),
        ("Jabón en polvo Alta Espuma", "Rindex", "Jabón en polvo", "3 kg", 8760,
         "Para lavado a mano y lavarropas de carga superior."),
        ("Jabón en polvo Baja Espuma", "Rindex", "Jabón en polvo", "3 kg", 8980,
         "Formulado para lavarropas automáticos de carga frontal."),
        ("Jabón en polvo con oxígeno activo", "UltraClean", "Jabón en polvo", "2,5 kg", 9640,
         "El oxígeno activo despega manchas sin dañar las fibras."),
        ("Cápsulas de lavado 3 en 1", "UltraClean", "Cápsulas", "20 un.", 11200,
         "Jabón, quitamanchas y suavizante en una sola cápsula."),
        ("Cápsulas de lavado ropa oscura", "UltraClean", "Cápsulas", "15 un.", 9880,
         "Evita el desgaste gris de jeans y prendas negras."),
        ("Jabón en pan para ropa", "Rindex", "Barras", "200 g", 1290,
         "El clásico pan de jabón para prelavar puños y cuellos."),
        ("Jabón en pan blanqueador", "Nevada", "Barras", "300 g", 1690,
         "Con azulete tradicional para prendas blancas."),
        ("Limpiador de lavarropas", "CleanPro", "Mantenimiento", "250 ml", 4890,
         "Elimina residuos de jabón y sarro del tambor cada 2 meses."),
    ],
    # ------------------------------------------------------- desinfectantes --
    "desinfectantes": [
        ("Lavandina común", "Nevada", "Lavandinas", "1 L", 1490,
         "Concentración de 55 g/l Cl para desinfección general."),
        ("Lavandina en gel", "Nevada", "Lavandinas", "1 L", 2380,
         "Densidad extra para que actúe más tiempo sobre la superficie."),
        ("Lavandina perfumada Lavanda", "Nevada", "Lavandinas", "2 L", 2890,
         "El poder de la lavandina con aroma agradable y persistente."),
        ("Lavandina apta ropa de color", "Nevada", "Lavandinas", "1,8 L", 3480,
         "Desinfecta sin decolorar prendas de color."),
        ("Desinfectante de superficies aerosol", "Vitalix", "Aerosoles", "360 ml", 4290,
         "Elimina el 99,9% de virus y bacterias en 30 segundos."),
        ("Desinfectante multiuso amonio cuaternario", "CleanPro", "Concentrados", "1 L", 5680,
         "Sanitizante profesional de quinta generación, sin enjuague."),
        ("Sanitizante de manos en spray", "Vitalix", "Aerosoles", "250 ml", 2340,
         "Formato de bolsillo con 70% de alcohol etílico."),
        ("Toallitas desinfectantes", "Vitalix", "Toallitas", "80 un.", 4180,
         "Listas para usar en picaportes, teclados y volantes."),
        ("Desinfectante para juguetes", "Suavia", "Concentrados", "500 ml", 4520,
         "Fórmula sin cloro, segura para superficies que van a la boca."),
        ("Alcohol líquido 70%", "Vitalix", "Alcoholes", "1 L", 3120,
         "Alcohol etílico rectificado listo para usar."),
        ("Agua oxigenada 10 volúmenes", "Vitalix", "Alcoholes", "500 ml", 1780,
         "Uso doméstico para desinfección y blanqueo de textiles."),
    ],
    # ----------------------------------------------------------- detergentes --
    "detergentes": [
        ("Detergente concentrado Limón", "Espumel", "Vajilla", "750 ml", 3290,
         "Una gota lava hasta 40 platos: máxima concentración."),
        ("Detergente concentrado Manzana", "Espumel", "Vajilla", "750 ml", 3290,
         "Corta la grasa con aroma frutal y enjuague rápido."),
        ("Detergente concentrado Aloe", "Espumel", "Vajilla", "500 ml", 2740,
         "Con aloe vera para cuidar las manos durante el lavado."),
        ("Detergente bidón económico", "Espumel", "Vajilla", "5 L", 12900,
         "Formato familiar para recargar el envase con gatillo."),
        ("Detergente antibacterial", "Vitalix", "Vajilla", "500 ml", 3680,
         "Higieniza esponjas y utensilios además de lavar la vajilla."),
        ("Detergente para lavavajillas en polvo", "CleanPro", "Lavavajillas", "1 kg", 7480,
         "Formulado para máquinas: sin espuma y con abrillantador."),
        ("Pastillas para lavavajillas", "CleanPro", "Lavavajillas", "30 un.", 9860,
         "Todo en uno: detergente, sal y abrillantador."),
        ("Abrillantador de enjuague", "CleanPro", "Lavavajillas", "500 ml", 5240,
         "Evita las manchas de agua en copas y cubiertos."),
        ("Sal para lavavajillas", "CleanPro", "Lavavajillas", "2 kg", 4380,
         "Ablanda el agua y protege la máquina del sarro."),
        ("Detergente ecológico biodegradable", "Verdalia", "Vajilla", "750 ml", 4190,
         "Tensioactivos de origen vegetal, envase reciclado."),
        ("Detergente industrial neutro", "Duramax", "Vajilla", "5 L", 14800,
         "Bidón para gastronomía, apto contacto con alimentos."),
    ],
    # --------------------------------------------------------- aromatizantes --
    "aromatizantes": [
        ("Aromatizante de ambientes Vainilla", "Aromia", "Ambientales", "360 ml", 3180,
         "Aroma cálido y envolvente que dura hasta 6 horas."),
        ("Aromatizante de ambientes Lavanda", "Aromia", "Ambientales", "360 ml", 3180,
         "Fragancia relajante ideal para dormitorios."),
        ("Aromatizante de ambientes Frutos Rojos", "Aromia", "Ambientales", "360 ml", 3180,
         "Nota frutal intensa para livings y comedores."),
        ("Aromatizante textil Algodón", "Aromia", "Textiles", "500 ml", 3890,
         "Perfuma cortinas, sillones y ropa de cama sin manchar."),
        ("Difusor de varillas Bambú", "Aromia", "Difusores", "180 ml", 6740,
         "Difusión continua durante 60 días con varillas de rattan."),
        ("Difusor de varillas Sándalo", "Aromia", "Difusores", "180 ml", 6740,
         "Aroma amaderado de larga duración para el ambiente."),
        ("Repuesto para difusor eléctrico", "Aromia", "Difusores", "20 ml", 3420,
         "Compatible con difusores eléctricos estándar."),
        ("Vela aromática Citronella", "Verdalia", "Velas", "200 g", 4290,
         "Ahuyenta mosquitos en patios y balcones hasta 25 horas."),
        ("Vela aromática Coco y Vainilla", "Verdalia", "Velas", "200 g", 4590,
         "Cera de soja con mecha de algodón, sin humo negro."),
        ("Neutralizador de olores mascotas", "Vitalix", "Neutralizadores", "500 ml", 4680,
         "Encapsula el olor con enzimas en lugar de perfumarlo."),
        ("Neutralizador de olor a humo", "Vitalix", "Neutralizadores", "400 ml", 4380,
         "Elimina el olor a cigarrillo de cortinas y tapizados."),
        ("Aromatizante de auto colgante", "Aromia", "Auto", "1 un.", 1490,
         "Cartón perfumado con aroma a auto nuevo, dura 30 días."),
    ],
    # ---------------------------------------------------------------- papel --
    "papel": [
        ("Papel higiénico doble hoja 4 rollos", "Papelia", "Papel higiénico", "4 x 30 m", 3690,
         "Doble hoja acolchada, suave y resistente en húmedo."),
        ("Papel higiénico doble hoja 12 rollos", "Papelia", "Papel higiénico", "12 x 30 m", 9980,
         "Pack familiar con el mejor precio por metro."),
        ("Papel higiénico simple hoja 4 rollos", "Papelia", "Papel higiénico", "4 x 80 m", 4290,
         "Rollo de larga duración, ideal para oficinas."),
        ("Papel higiénico húmedo", "Suavia", "Papel higiénico", "48 un.", 3480,
         "Biodegradable, con manzanilla, complementa el papel seco."),
        ("Rollo de cocina 3 unidades", "Papelia", "Rollos de cocina", "3 x 60 pañ.", 5120,
         "Alto poder absorbente, no se deshace al mojarse."),
        ("Rollo de cocina extra absorbente", "Papelia", "Rollos de cocina", "2 x 100 pañ.", 6240,
         "Cada paño absorbe hasta 8 veces su peso en líquido."),
        ("Servilletas de papel 100 unidades", "Papelia", "Servilletas", "100 un.", 1890,
         "Servilleta clásica de mesa, hoja simple."),
        ("Servilletas doble hoja premium", "Papelia", "Servilletas", "60 un.", 2680,
         "Gofradas y con relieve, para mesas de fiesta."),
        ("Pañuelos descartables caja", "Suavia", "Pañuelos", "100 un.", 2340,
         "Triple hoja con bálsamo, suaves para la nariz."),
        ("Toallas de papel intercaladas", "Papelia", "Institucional", "250 un.", 6890,
         "Para dispenser de baño institucional, hoja simple."),
        ("Bolsas de residuo 45x60", "Fibrex", "Bolsas", "20 un.", 2790,
         "Reforzadas en la base, ideales para cocina."),
        ("Bolsas de residuo 60x90 reforzadas", "Fibrex", "Bolsas", "10 un.", 3480,
         "Consorcio: soportan hasta 20 kg sin romperse."),
        ("Bolsas de residuo con manija", "Fibrex", "Bolsas", "30 un.", 3980,
         "Cierre fácil con manijas, evita derrames al transportar."),
        ("Bolsas compostables", "Verdalia", "Bolsas", "15 un.", 4290,
         "Se degradan en 180 días, aptas para residuos orgánicos."),
    ],
    # ---------------------------------------------------------- accesorios --
    "accesorios": [
        ("Esponja doble faz pack x3", "Fibrex", "Esponjas", "3 un.", 1780,
         "Cara de fibra verde para lo difícil y esponja para lo delicado."),
        ("Esponja antirrayas para teflón", "Fibrex", "Esponjas", "2 un.", 2140,
         "No raya sartenes antiadherentes ni vidrio."),
        ("Fibra esponja gigante", "Fibrex", "Esponjas", "1 un.", 1490,
         "Formato grande para bachas y superficies amplias."),
        ("Guantes de látex talle M", "Fibrex", "Guantes", "1 par", 2290,
         "Interior afelpado y puño largo que protege la muñeca."),
        ("Guantes de látex talle L", "Fibrex", "Guantes", "1 par", 2290,
         "Antideslizantes en la palma, resistentes a detergentes."),
        ("Guantes descartables x100", "Vitalix", "Guantes", "100 un.", 5890,
         "Nitrilo sin polvo, para tareas de higiene o cocina."),
        ("Trapo de piso algodón", "Fibrex", "Trapos", "1 un.", 2480,
         "Algodón de primera, absorbe sin dejar pelusa."),
        ("Trapo rejilla pack x3", "Fibrex", "Trapos", "3 un.", 2190,
         "Rejilla multiuso de secado rápido para cocina."),
        ("Paño de microfibra x4", "CleanPro", "Trapos", "4 un.", 4380,
         "Levanta el polvo sin productos, lavable 300 veces."),
        ("Escoba de cerda suave con cabo", "Duramax", "Escobas", "1 un.", 6480,
         "Cerda sintética que no marca el piso, cabo de 120 cm."),
        ("Escoba de cerda dura exterior", "Duramax", "Escobas", "1 un.", 7290,
         "Para patios, veredas y superficies rugosas."),
        ("Secador de piso 45 cm", "Duramax", "Secadores", "1 un.", 5890,
         "Goma doble labio que no deja marcas de agua."),
        ("Mopa de microfibra giratoria", "CleanPro", "Mopas", "1 un.", 12400,
         "Cabezal 360° con repuesto lavable incluido."),
        ("Repuesto de mopa de microfibra", "CleanPro", "Mopas", "1 un.", 4980,
         "Compatible con mopas giratorias estándar."),
        ("Balde con escurridor 12 L", "Duramax", "Baldes", "12 L", 11800,
         "Sistema de escurrido a pedal, plástico reforzado."),
        ("Balde plástico reforzado 10 L", "Duramax", "Baldes", "10 L", 4290,
         "Con manija metálica y pico vertedor."),
        ("Cepillo para inodoro con base", "Fibrex", "Cepillos", "1 un.", 3890,
         "Base cerrada que oculta el cepillo y evita salpicaduras."),
        ("Cepillo de mano multiuso", "Fibrex", "Cepillos", "1 un.", 2180,
         "Cerda dura para zócalos, juntas y calzado."),
        ("Plumero atrapapolvo extensible", "PuroHogar", "Plumeros", "1 un.", 5480,
         "Se extiende hasta 1,80 m para techos y ventiladores."),
        ("Pala recogedora con goma", "Duramax", "Escobas", "1 un.", 3290,
         "Borde de goma que no deja la línea de tierra."),
        ("Set de limpieza 5 piezas", "Duramax", "Sets", "5 piezas", 18900,
         "Escoba, pala, secador, balde y trapo en un solo pack."),
        ("Rociador vacío reutilizable", "Fibrex", "Sets", "500 ml", 1690,
         "Gatillo regulable para preparar tus propias diluciones."),
    ],
    # ---------------------------------------------------------------- pisos --
    "pisos": [
        ("Limpiador de pisos Lavanda", "Brillex", "Limpiapisos", "1,8 L", 3890,
         "Perfume que permanece hasta 12 horas después del trapeado."),
        ("Limpiador de pisos Bebé", "Suavia", "Limpiapisos", "1,8 L", 4190,
         "Sin amoníaco, pensado para hogares con chicos gateando."),
        ("Limpiador de pisos Pino", "Brillex", "Limpiapisos", "1,8 L", 3890,
         "El clásico aroma a pino con acción desinfectante."),
        ("Limpiador de pisos concentrado", "Rindex", "Limpiapisos", "900 ml", 4680,
         "Media tapita por balde: rinde el triple que un limpiador común."),
        ("Limpiador para pisos de madera", "PuroHogar", "Maderas", "750 ml", 6240,
         "Limpia sin humedecer en exceso el entablonado."),
        ("Cera líquida incolora", "PuroHogar", "Ceras", "900 ml", 5480,
         "Autobrillante, no requiere lustrado posterior."),
        ("Cera líquida color roble", "PuroHogar", "Ceras", "900 ml", 5680,
         "Disimula rayones y unifica el tono de la madera."),
        ("Cera en pasta para parquet", "PuroHogar", "Ceras", "500 g", 6890,
         "Nutre y protege el parquet con acabado semi mate."),
        ("Limpiador para porcelanato", "CleanPro", "Cerámicos", "1 L", 5120,
         "Evita la película opaca que dejan los limpiadores comunes."),
        ("Removedor de cera", "Duramax", "Mantenimiento", "1 L", 6480,
         "Elimina capas viejas de cera antes de renovar el piso."),
        ("Limpiador de alfombras en polvo", "Espumel", "Alfombras", "500 g", 4890,
         "Se esparce, se deja actuar y se aspira: sin secado."),
        ("Antideslizante para pisos", "Duramax", "Mantenimiento", "1 L", 7290,
         "Tratamiento invisible que reduce el riesgo de resbalones."),
    ],
    # ----------------------------------------------------------------- ropa --
    "ropa": [
        ("Suavizante concentrado Primavera", "Suavia", "Suavizantes", "900 ml", 4290,
         "Tres tapitas por lavado: perfume floral de larga duración."),
        ("Suavizante concentrado Bebé", "Suavia", "Suavizantes", "900 ml", 4590,
         "Hipoalergénico, deja las prendas suaves y sin perfume fuerte."),
        ("Suavizante Clásico Azul", "Suavia", "Suavizantes", "3 L", 8480,
         "Formato familiar del suavizante de toda la vida."),
        ("Suavizante con protección de color", "Suavia", "Suavizantes", "1,8 L", 6890,
         "Reduce el desgaste de las fibras y mantiene el color."),
        ("Quitamanchas líquido en gatillo", "UltraClean", "Quitamanchas", "500 ml", 3980,
         "Se aplica directo sobre la mancha antes del lavado."),
        ("Quitamanchas en polvo con oxígeno", "UltraClean", "Quitamanchas", "1 kg", 6480,
         "Para prelavado en remojo de manchas difíciles."),
        ("Quitamanchas para ropa blanca", "Nevada", "Quitamanchas", "500 ml", 4120,
         "Devuelve el blanco sin el amarilleo del cloro."),
        ("Quitamanchas de grasa y aceite", "UltraClean", "Quitamanchas", "250 ml", 3690,
         "Específico para manchas de comida, motor y cosmética."),
        ("Perfume para ropa concentrado", "Aromia", "Perfumantes", "250 ml", 5240,
         "Se agrega al enjuague: hasta 30 días de fragancia."),
        ("Almidón en aerosol", "Nevada", "Planchado", "360 ml", 3480,
         "Facilita el planchado y da cuerpo a camisas y manteles."),
        ("Agua de planchado perfumada", "Aromia", "Planchado", "1 L", 4180,
         "Sin minerales: no obstruye la plancha a vapor."),
        ("Bolsa de lavado para delicados", "Fibrex", "Accesorios", "2 un.", 2890,
         "Protege lencería y prendas de lana en el lavarropas."),
        ("Quitapelusas manual", "Fibrex", "Accesorios", "1 un.", 3290,
         "Rodillo adhesivo recargable para sacos y tapizados."),
    ],
    # --------------------------------------------------------- profesional --
    "profesional": [
        ("Detergente industrial bidón", "Duramax", "Bidones", "20 L", 42800,
         "Alto rendimiento para cocinas industriales y comedores."),
        ("Desinfectante concentrado bidón", "CleanPro", "Bidones", "20 L", 48900,
         "Amonio cuaternario de quinta generación para grandes superficies."),
        ("Limpiapisos institucional bidón", "Duramax", "Bidones", "20 L", 36400,
         "Diluye 1:40, pensado para escuelas y oficinas."),
        ("Desengrasante industrial", "Duramax", "Concentrados", "5 L", 18900,
         "Ataca grasa de maquinaria y pisos de taller."),
        ("Jabón espuma para dispenser", "Vitalix", "Dispensers", "5 L", 16800,
         "Recarga universal para dispensers de espuma."),
        ("Alcohol en gel bidón", "Vitalix", "Bidones", "5 L", 14900,
         "Recarga para totems y dispensers de ingreso."),
        ("Papel higiénico institucional", "Papelia", "Institucional", "8 x 300 m", 24800,
         "Rollo de gran metraje para dispenser industrial."),
        ("Toallas intercaladas institucional", "Papelia", "Institucional", "2500 un.", 28900,
         "Caja mayorista para baños de alto tránsito."),
        ("Bolsas consorcio 90x120", "Fibrex", "Institucional", "100 un.", 18400,
         "Espesor reforzado para residuos de edificios y comercios."),
        ("Carro de limpieza profesional", "Duramax", "Equipamiento", "1 un.", 128900,
         "Con balde doble, prensa mopa y bolsa de residuos."),
        ("Mopa profesional con repuestos", "CleanPro", "Equipamiento", "1 un.", 34900,
         "Sistema de cambio rápido con 3 repuestos de microfibra."),
        ("Cartelería piso mojado", "Duramax", "Equipamiento", "2 un.", 12400,
         "Señalización plegable obligatoria para espacios públicos."),
        ("Guantes de trabajo reforzados", "Fibrex", "Seguridad", "1 par", 6890,
         "Látex de alto espesor con puño extralargo."),
        ("Barbijos descartables x50", "Vitalix", "Seguridad", "50 un.", 7480,
         "Triple capa con clip nasal ajustable."),
    ],
}


def total_products() -> int:
    return sum(len(items) for items in PRODUCTS.values())
